version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"  # Root-level go.mod
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/docs"  # go.mod inside the docs folder
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"  # GitHub Actions workflows
    schedule:
      interval: "weekly"
